name: Build Hope Out APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual trigger

jobs:
  build-apk:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.1'
        channel: 'stable'
        
    - name: Get dependencies
      run: flutter pub get
      
    - name: Analyze code
      run: flutter analyze
      
    - name: Run tests
      run: flutter test
      continue-on-error: true  # Don't fail if tests have issues
      
    - name: Build APK
      run: flutter build apk --debug
      
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: hope-out-debug-apk
        path: build/app/outputs/flutter-apk/app-debug.apk
        retention-days: 30
        
    - name: Create Release (if on main/master)
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.0.${{ github.run_number }}
        name: Hope Out v1.0.${{ github.run_number }}
        body: |
          🚀 **Hope Out - Neighborhood Social App**
          
          **What's New:**
          - Beautiful splash screen and onboarding
          - Email and Google authentication
          - Home dashboard with community features
          - Firebase integration ready
          - Cross-platform support
          
          **Installation:**
          1. Download the APK file below
          2. Enable "Unknown sources" in Android settings
          3. Install the APK on your Android device
          4. Open Hope Out and enjoy!
          
          **Features:**
          - ✅ Splash screen with animations
          - ✅ User authentication (Email/Google)
          - ✅ Home dashboard
          - ✅ Firebase test tools
          - ✅ Platform-aware design
          
          Built automatically with GitHub Actions 🤖
        files: build/app/outputs/flutter-apk/app-debug.apk
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
